services:
  mysql:
    image: mysql:8.3.0
    container_name: lotto-challenge
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql/lotto-challenge:/var/lib/mysql
      - ./data/mysql/config/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lotto-challenge
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci